name: Build NEAR Contract with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build NEAR contract in Docker

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Build
      run: |
        docker build -t near-contract-builder .

    - name: Run Build Script in Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace near-contract-builder /workspace/contract/.build.sh

    # You can add additional Docker steps or any other steps as needed
