name: Build NEAR Contract with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build NEAR contract in Docker

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: List Directory Structure in Docker
      run: |
        docker pull nearprotocol/contract-builder@sha256:53b34ea28b8995c6e8908e76db8ea0b117ac73bc91c83c8aae930e635e9ef885
        docker run --rm -v ${{ github.workspace }}:/workspace nearprotocol/contract-builder@sha256:53b34ea28b8995c6e8908e76db8ea0b117ac73bc91c83c8aae930e635e9ef885 ls -R /workspace
